#!/bin/sh /etc/rc.common
USE_PROCD=1
START=96
STOP=10

start_service() {
  procd_open_instance
  procd_set_param command /usr/bin/fapanister-recovery-v2-poll
  procd_set_param respawn 10 5 0
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_close_instance
}
